services:
  scraper:
    build: .
    container_name: assectra_scraper
    env_file:
      - .env
    volumes:
      # Mapeia o código-fonte para o contêiner. Isso permite que o nodemon
      # (rodando no contêiner) detecte mudanças feitas na sua máquina
      # e reinicie o script automaticamente.
      - ./src:/usr/src/app/src
      # Mapeia a pasta de saída para que os arquivos gerados no contêiner
      # fiquem disponíveis na sua máquina.
      - ./output:/usr/src/app/output
