version: '3.8'

services:
  scraper:
    build: .
    container_name: assectra_scraper
    env_file:
      - .env
    # Para desenvolvimento: sincroniza o código-fonte para dentro do container.
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
    # Para dados persistentes: mapeia a pasta de saída para que os arquivos
    # gerados no container fiquem disponíveis na sua máquina.
    volumes:
      - ./output:/usr/src/app/output
